# Generated by Django 5.2.3 on 2025-06-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
